entry: MainTask
id: click_log_button
name: 窗口点击-1
script: main.py
target_window:
  hwnd: null
  process_name: msedge.exe
  title_contains: WinAutoClick 和另外 2 个页面 - 个人 - Microsoft​ Edge
templates: F:/各类脚本/2025.11.15-自动点击脚本/WinAutoClick/WinAutoClick/tasks/click_log_button/templates.yaml
